const fs = require("fs");
const data = {
  project: {
    name: "SIYL",
    tagline: "Find Professionals Who Speak Your Language",
    description:
      "A web platform connecting expats and international residents in Italy with trusted local professionals who speak their language — from accountants to doctors to real estate agents. Launch is Italy-only.",
    client: "Margaret Vella",
    contact: "margaret.vella@gmail.com",
    date: "April 2026",
    geo: "Italy only — geolocation restrictions applied at launch",
    stack: ["Nuxt.js 3", "Vue 3", "PostgreSQL", "Stripe", "Google OAuth", "Tailwind CSS"],
  },
  summary: {
    totalHours: 560,
    totalDays: 70,
    phases: 3,
    note: "70 working days × 8 hours — one developer, full project",
    outOfScope: [
      "Mobile app (iOS and Android)",
      "Professional SEO strategy and content campaign",
      "Professional UI/UX design and brand identity",
      "Digital marketing and paid advertising",
      "Expansion outside Italy (Phase 3 covers web-only national expansion)",
      "Partnership and affiliate programme management",
      "Legal advice or GDPR legal counsel (technical implementation only)",
    ],
    hoursBreakdown: [
      { label: "Building the website", hours: 110, plain: "All the pages, buttons, and screens users see and interact with." },
      { label: "Building the engine", hours: 90, plain: "The invisible logic that makes everything work: bookings, logins, payments." },
      { label: "Database setup", hours: 20, plain: "Designing and setting up where all data is stored securely." },
      { label: "Connecting external services", hours: 52, plain: "Authentication, payment, identity verification, document scanning." },
      { label: "Servers and deployment", hours: 36, plain: "Setting up hosting, security, and going live." },
      { label: "Documentation and compliance", hours: 14, plain: "Technical records, GDPR requirements, and cookie policy setup." },
      { label: "Testing and quality checks", hours: 18, plain: "Making sure everything works correctly before launch." },
    ],
  },
  externalApis: {
    title: "External Services Used",
    note: "The following third-party services are integrated into the platform. Each requires its own account and may have its own pricing.",
    items: [
      {
        category: "Authentication",
        service: "Google OAuth 2.0",
        use: "Allows users and professionals to log in with their Google account — one click, no extra password needed.",
        phase: 1,
      },
      {
        category: "Payment",
        service: "Stripe",
        use: "Handles all subscription billing for professionals. SIYL never stores any card or bank details — Stripe manages this entirely.",
        phase: 1,
      },
      {
        category: "Identity Verification",
        service: "VIES (EU VAT validation API)",
        use: "Checks that the Italian VAT number (Partita IVA) entered by a professional is real and active before the account is created.",
        phase: 1,
      },
      {
        category: "Document Scanning (OCR)",
        service: "Google Document AI",
        use: "Reads and extracts data from uploaded certification documents. The document is processed and then automatically deleted within 48 hours — nothing sensitive is stored permanently.",
        phase: 1,
      },
      {
        category: "Calendar Sync",
        service: "Google Calendar, Microsoft Outlook, Apple iCal",
        use: "Professionals can optionally connect their existing calendar. Confirmed bookings are added automatically and SIYL checks for conflicts before confirming appointments.",
        phase: 1,
      },
      {
        category: "Address Search",
        service: "Google Places API",
        use: "Smart address autocomplete when professionals enter their business location — reduces typos and ensures valid addresses.",
        phase: 1,
      },
      {
        category: "Email Notifications",
        service: "Resend (or SendGrid)",
        use: "Sends all transactional emails: booking confirmations, cancellation notices, review requests, subscription updates.",
        phase: 1,
      },
    ],
  },
  phases: [
    {
      id: 1,
      name: "Phase 1",
      label: "Version 1 — Ready to Launch",
      color: "red",
      totalHours: 340,
      description:
        "Everything needed to go live. Professionals create verified profiles, users search and book appointments, payments go through Stripe, and an admin panel lets you manage everything.",
      whatYouGet: [
        "Professionals register, complete their profile, and get your approval before appearing publicly",
        "Users search for professionals by language, profession, and location — Italy only at launch",
        "Booking system with automatic calendar slots — double-bookings are technically prevented",
        "Stripe payments: Basic plan (70/month) and Premium plan (100/month) — no banking details stored",
        "Secure messaging between users and professionals, only available after a confirmed booking",
        "Admin panel: approve profiles, moderate content, suspend accounts, view reports",
        "Automatic email notifications for bookings, cancellations, and payment events",
        "GDPR-compliant data handling, cookie policy, and privacy notice (technical setup — legal counsel separate)",
        "SEO-friendly page structure and URLs — professional SEO campaign is the client's responsibility",
      ],
      breakdown: [
        { label: "Website", hours: 110 },
        { label: "Engine", hours: 90 },
        { label: "Database", hours: 20 },
        { label: "External services", hours: 52 },
        { label: "Servers and deployment", hours: 36 },
        { label: "Documentation and compliance", hours: 14 },
        { label: "Testing", hours: 18 },
      ],
      areas: [
        {
          name: "Building the Website",
          plainName: "Everything users see on screen",
          hours: 110,
          icon: "screen",
          items: [
            { task: "Homepage — search bar, language and location filters, featured professionals", hours: 6 },
            { task: "Sign up and login pages for both professionals and regular users", hours: 7 },
            { task: "Professional dashboard — upcoming bookings, profile status, and notifications at a glance", hours: 7 },
            { task: "Profile setup page — personal details, certifications, languages spoken", hours: 10 },
            { task: "Video recording — professionals record a short intro video directly in the browser", hours: 8 },
            { task: "Services page — list what they offer, pricing, and session duration", hours: 5 },
            { task: "Availability calendar — set working hours and block specific days off", hours: 11 },
            { task: "Booking flow — user picks a time slot, selects a service, and confirms", hours: 8 },
            { task: "Messaging screen — one conversation per confirmed appointment, with unread indicators", hours: 9 },
            { task: "Payment page — pick a subscription plan and pay securely via Stripe", hours: 6 },
            { task: "Public profile — what users see when browsing a professional", hours: 7 },
            { task: "User appointments page — view past and upcoming bookings, cancel if needed", hours: 5 },
            { task: "Reviews — star ratings and written comments after a completed appointment", hours: 4 },
            { task: "Admin panel — approve profiles, manage users, view reports, moderate content", hours: 13 },
            { task: "Basic SEO-friendly page structure — pro SEO strategy is the client's responsibility", hours: 4 },
          ],
        },
        {
          name: "Building the Engine",
          plainName: "The invisible logic behind the scenes",
          hours: 90,
          icon: "gear",
          items: [
            { task: "Account system: register, log in, verify email, and reset password", hours: 9 },
            { task: "Italian VAT number (Partita IVA) validation at registration", hours: 5 },
            { task: "Professional profile management with admin approval workflow", hours: 11 },
            { task: "Booking engine — creates appointments, prevents double-bookings, handles cancellations", hours: 12 },
            { task: "Messaging system with GDPR access logs — every message access is recorded as required by EU law", hours: 9 },
            { task: "Stripe subscription management — payment success, failure, and grace period logic", hours: 9 },
            { task: "Review system — verified internal reviews (real bookings only) and manually added external ones", hours: 6 },
            { task: "Admin tools — suspend accounts, approve profiles, and generate reports", hours: 7 },
            { task: "Notification engine — triggers emails and in-app alerts on key events", hours: 5 },
            { task: "Certification processing — extracts data from uploaded documents, then automatically deletes the file", hours: 5 },
            { task: "Video moderation queue — flags videos for admin review before they go live", hours: 4 },
            { task: "GDPR and cookie policy technical setup — consent management and data access rules", hours: 5 },
            { task: "Italy-only geolocation + timezone handling — stored in UTC, shown in Italian local time", hours: 4 },
            { task: "Reporting — booking stats, active users, and subscription data for the admin", hours: 5 },
            { task: "SEO-friendly URLs, meta tags, and basic sitemap", hours: 4 },
          ],
        },
        {
          name: "Database Setup",
          plainName: "Where all the data lives",
          hours: 20,
          icon: "database",
          items: [
            { task: "Design the data structure — users, bookings, messages, reviews, and payment records", hours: 8 },
            { task: "Search optimisation — fast filtering by language, profession, and location in Italy", hours: 4 },
            { task: "GDPR-compliant log tables — who accessed what and when, stored as required by EU law", hours: 4 },
            { task: "Test data setup for development and pre-launch testing", hours: 4 },
          ],
        },
        {
          name: "Connecting External Services",
          plainName: "Authentication · Payment · Identity · Document scanning",
          hours: 52,
          icon: "link",
          items: [
            { task: "Authentication — Google OAuth 2.0: one-click login for both professionals and users", hours: 6 },
            { task: "Payment — Stripe: subscriptions, automatic renewals, failed payment handling, no card data stored", hours: 13 },
            { task: "Calendar sync — Google Calendar: check availability and add confirmed bookings automatically", hours: 10 },
            { task: "Calendar sync — Microsoft Outlook and Apple Calendar support", hours: 5 },
            { task: "Address search — Google Places API: smart address autocomplete for professional location", hours: 4 },
            { task: "Email notifications — Resend: booking confirmations, reminders, and review requests", hours: 7 },
            { task: "Document scanning (OCR) — Google Document AI: extracts certification data, file deleted within 48 hours", hours: 5 },
            { task: "Identity check — VIES (EU VAT API): validates Italian Partita IVA before account creation", hours: 2 },
          ],
        },
        {
          name: "Servers and Going Live",
          plainName: "Hosting, security, and deployment",
          hours: 36,
          icon: "server",
          items: [
            { task: "Set up three environments: development, testing, and production — so changes are tested before going live", hours: 8 },
            { task: "File and video storage — secure cloud storage with automatic cleanup rules", hours: 7 },
            { task: "Automated deployment — when code is updated, the website updates automatically", hours: 8 },
            { task: "Domain, SSL certificate (the HTTPS padlock), and DNS setup", hours: 4 },
            { task: "Error monitoring and uptime alerts — you get notified if something breaks", hours: 6 },
            { task: "Security review — protection against the most common web attacks", hours: 3 },
          ],
        },
        {
          name: "Documentation and Compliance",
          plainName: "Written records, GDPR, and cookie policy",
          hours: 14,
          icon: "doc",
          items: [
            { task: "Technical guide — how the system parts communicate and how to maintain them", hours: 5 },
            { task: "Database map — what each table stores and why", hours: 3 },
            { task: "GDPR technical records — data flow documentation and processing records (legal counsel is separate)", hours: 3 },
            { task: "Cookie policy setup — consent banner and technical cookie management", hours: 3 },
          ],
        },
        {
          name: "Testing and Quality Checks",
          plainName: "Making sure nothing breaks before launch",
          hours: 18,
          icon: "test",
          items: [
            { task: "Automated tests for key flows: login, booking, payment, and admin actions", hours: 8 },
            { task: "Manual testing across different browsers and screen sizes (desktop and mobile)", hours: 6 },
            { task: "Full end-to-end test: a real user registers, finds a professional, and books an appointment", hours: 4 },
          ],
        },
      ],
    },
    {
      id: 2,
      name: "Phase 2",
      label: "Version 2 — After Launch",
      color: "stone",
      totalHours: 140,
      description:
        "Once the website is live and you have real users, these improvements are added based on actual feedback. Nothing here is guesswork — it is built on what your users actually need.",
      whatYouGet: [
        "Full Italian and English interface, expandable to more languages",
        "Advanced search: filter by rating, distance, and sort results",
        "Studio and agency accounts — one profile managing multiple professionals underneath",
        "Analytics for professionals: how many people viewed their profile and how many booked",
        "Push notifications on phones and desktops without a mobile app",
        "Performance improvements for faster page loads as user numbers grow",
        "CSV and Excel data exports so you can analyse your business numbers",
      ],
      breakdown: [
        { label: "Multi-language and search", hours: 42 },
        { label: "Studio accounts and analytics", hours: 36 },
        { label: "Notifications and premium features", hours: 30 },
        { label: "Performance, exports, and promos", hours: 32 },
      ],
      areas: [
        {
          name: "New Features and Improvements",
          plainName: "What gets added after launch, based on real feedback",
          hours: 140,
          icon: "rocket",
          items: [
            { task: "Multi-language interface — full Italian and English, expandable to more languages", hours: 24 },
            { task: "Advanced search filters — sort by rating, distance, and availability", hours: 18 },
            { task: "Studio and agency accounts — one profile managing multiple professionals underneath", hours: 20 },
            { task: "Analytics for professionals — profile views and booking conversion rates", hours: 14 },
            { task: "Push notifications — real-time alerts on phones and desktops, no app needed", hours: 14 },
            { task: "Premium user subscriptions — optional paid features for clients (to be defined after launch)", hours: 14 },
            { task: "Performance improvements — faster loads, smarter caching as traffic grows", hours: 16 },
            { task: "Referral and promo code system", hours: 12 },
            { task: "CSV and Excel export of admin reports", hours: 8 },
          ],
        },
      ],
    },
    {
      id: 3,
      name: "Phase 3",
      label: "Version 3 — Scaling the Web Platform",
      color: "warm",
      totalHours: 80,
      description:
        "If SIYL grows beyond its initial launch, this phase extends the web platform with smarter features: AI-powered matching, video consultations, B2B accounts for organisations, and national expansion within Italy.",
      whatYouGet: [
        "Expand to more Italian regions and cities on the same web platform",
        "AI-powered matching — automatically suggest the best professional for each user",
        "Video consultations built directly into the website — no Zoom or third-party tools needed",
        "B2B accounts for organisations, law firms, embassies, and relocation agencies",
        "Advanced analytics and business intelligence dashboard for the admin",
      ],
      outOfScope: [
        "Mobile app (iOS and Android) — this is a separate project and not part of this estimate",
        "Expansion outside Europe — requires separate legal and compliance work",
        "Professional UI/UX redesign — this estimate covers functional design only",
        "SEO strategy and content campaign — this is the client's responsibility",
        "Digital marketing, paid advertising, and social media management",
        "Partnership and affiliate programme management",
      ],
      breakdown: [
        { label: "Multi-region expansion", hours: 20 },
        { label: "AI matching", hours: 20 },
        { label: "Video consultations", hours: 20 },
        { label: "B2B accounts and analytics", hours: 20 },
      ],
      areas: [
        {
          name: "Web Platform Expansion",
          plainName: "Growing the platform across Italy",
          hours: 80,
          icon: "globe",
          items: [
            { task: "Expand to more Italian regions and cities — reuse the same platform structure", hours: 20 },
            { task: "AI professional matching — suggest the best professional based on user needs and history", hours: 20 },
            { task: "Built-in video consultations — users and professionals meet online directly on the platform", hours: 20 },
            { task: "B2B and organisation accounts — for embassies, law firms, relocation agencies", hours: 12 },
            { task: "Advanced business intelligence dashboard for the admin", hours: 8 },
          ],
        },
      ],
    },
  ],
  thirdPartyCosts: {
    note: "These are the monthly costs for running the website — separate from the development fee. Think of them like rent and utilities. Prices grow only if your user base grows.",
    vercel: {
      label: "Vercel",
      tag: "Free tier available",
      description: "Easiest to set up. Ideal for launch. Scales automatically. The website only runs when someone visits it.",
      freeTier:
        "Free tier includes unlimited bandwidth, custom domain, and automatic HTTPS. Upgrade to Pro (~20/month) once you need team access or higher limits.",
      costs: [
        {
          service: "Website hosting (Vercel Pro)",
          monthly: "0 to 20/mo",
          notes: "Free tier is enough for early stage. Pro adds team features and higher limits.",
        },
        {
          service: "Database (Neon PostgreSQL)",
          monthly: "approx 19 to 69/mo",
          notes: "Free tier available (0.5 GB). Scale plan for multiple branches and auto-suspend when idle.",
        },
        {
          service: "File and video storage (Cloudflare R2)",
          monthly: "approx 5 to 30/mo",
          notes: "No egress fees — you are not charged for people downloading files.",
        },
        { service: "Email notifications (Resend)", monthly: "0 to 20/mo", notes: "Free for 3,000 emails per month. 20/month for up to 50,000 emails." },
        { service: "Stripe payment processing", monthly: "Usage-based", notes: "1.5% plus 0.25 per successful payment — standard EU rate. No monthly fee." },
        {
          service: "Google APIs (address, document scanning)",
          monthly: "0 to 40/mo",
          notes: "Google gives 200 of free credit per month — covers most early usage entirely.",
        },
        { service: "Error monitoring (Sentry)", monthly: "0 to 26/mo", notes: "Free tier covers small teams. Alerts you when something breaks." },
      ],
      totalRange: "Approx 25 to 200 per month",
      atScale: "Approx 150 to 400 per month with 10,000+ professionals",
    },
    cloudflare: {
      label: "Cloudflare",
      tag: "Very generous free tier",
      description:
        "All-in-one platform: hosting, security, storage, and CDN under one roof. Exceptional free tier. Best value for money, especially at early stage.",
      freeTier:
        "Free tier includes: website hosting (Cloudflare Pages), 100,000 serverless function requests per day, 10 GB file storage (R2), DDoS protection, and global CDN — all at no cost.",
      costs: [
        {
          service: "Website hosting (Cloudflare Pages)",
          monthly: "0 to 20/mo",
          notes: "Free tier is very generous and covers most small to medium traffic levels.",
        },
        { service: "Serverless functions (Cloudflare Workers)", monthly: "0 to 5/mo", notes: "Free: 100,000 requests per day. Paid plan for higher volume." },
        {
          service: "File and video storage (Cloudflare R2)",
          monthly: "0 to 30/mo",
          notes: "Free: 10 GB storage included. No egress (download) fees — major cost saving.",
        },
        { service: "CDN and DDoS protection", monthly: "0/mo", notes: "Included free. Makes the website faster and shields it from attacks automatically." },
        {
          service: "Database (Neon PostgreSQL — external)",
          monthly: "approx 19 to 69/mo",
          notes: "Cloudflare D1 is an option but Neon is more robust for this project.",
        },
        { service: "Email notifications (Resend)", monthly: "0 to 20/mo", notes: "Same as other stacks." },
        { service: "Stripe payment processing", monthly: "Usage-based", notes: "1.5% plus 0.25 per transaction — EU standard." },
        { service: "Error monitoring (Sentry)", monthly: "0 to 26/mo", notes: "Free tier covers small teams." },
      ],
      totalRange: "Approx 20 to 170 per month",
      atScale: "Approx 100 to 350 per month — best value at any scale",
    },
    aws: {
      label: "AWS",
      tag: "For scale",
      description:
        "Most powerful and flexible option. No free tier for production use. Worth switching once you have consistent large traffic. Requires more technical management.",
      freeTier: "AWS Free Tier exists for new accounts (12 months) but is not suitable for production. Plan for full costs from the start.",
      costs: [
        { service: "Servers (AWS ECS Fargate)", monthly: "approx 50 to 200/mo", notes: "The computers that run the website. Scales with traffic." },
        { service: "Database (AWS RDS PostgreSQL)", monthly: "approx 50 to 150/mo", notes: "Managed database with automatic daily backups." },
        { service: "File storage (AWS S3)", monthly: "approx 5 to 40/mo", notes: "Videos, documents, and profile pictures." },
        { service: "Speed layer (AWS CloudFront CDN)", monthly: "approx 5 to 30/mo", notes: "Delivers the website fast to users across Italy and beyond." },
        { service: "Email (AWS SES)", monthly: "approx 1 to 10/mo", notes: "Very cost-effective. Requires domain verification." },
        { service: "Caching (Redis / ElastiCache)", monthly: "approx 25 to 80/mo", notes: "Makes repeated searches much faster. Important at scale." },
        { service: "Load balancer (AWS ALB)", monthly: "approx 18 to 35/mo", notes: "Routes traffic evenly when many users are online at once." },
        { service: "Stripe payment processing", monthly: "Usage-based", notes: "Same EU rate as other stacks." },
      ],
      totalRange: "Approx 155 to 545 per month",
      atScale: "Approx 500 to 1,200 per month at large scale",
    },
  },
  notes: [
    "This is a full-project estimate for one developer working alone from start to live website.",
    "Phase 1 at 340 hours: working full time (5 days a week) is roughly 9 to 10 weeks. At 3 days a week it is around 14 to 16 weeks.",
    "These are working estimates. If the scope changes mid-project — new features or a change of direction — hours will be adjusted and discussed.",
    "Professional SEO strategy and website design are the client's responsibility and are not included in this estimate.",
    "The website will be live in Italy only at launch. Geolocation is applied at server level — no extra cost.",
    "GDPR and cookie policy technical setup is included. Legal counsel and the official privacy policy text are the client's responsibility.",
    "Payment processing fees via Stripe are not included in the monthly cost estimate — they depend on subscription volume.",
    "Certification documents uploaded by professionals are scanned and automatically deleted within 48 hours. Nothing sensitive is permanently stored.",
    "The lean Cloudflare or Vercel stack is strongly recommended for launch: lower cost, easier to manage, no dedicated server to maintain.",
  ],
};

fs.writeFileSync("/Users/bammac2020/Sites/multi-professional-estimation/estimation.json", JSON.stringify(data, null, 2));
console.log(
  "Done. Total:",
  data.summary.totalHours,
  "h |",
  data.summary.totalDays,
  "days | phases:",
  data.phases.map((p) => p.name + ":" + p.totalHours + "h").join(", "),
);
